services:
    db:
        image: postgres:15-bullseye
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: passcheckdb
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"
                ]
            interval: 1s
            timeout: 1s
            retries: 100

    app:
        build: .
        ports:
            - 1337:1337
        command: bash -c "make initdb && make run"
        depends_on:
            db:
                condition: service_healthy
        environment:
            PYTHONUNBUFFERED: 1
            DB_HOST: db
            DB_USER: postgres
            DB_PASSWORD: postgres
            DB_NAME: passcheckdb
        volumes:
            - .:/usr/src/app

volumes:
    pgdata:


