services:
    db:
        image: postgres:15-bullseye
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: passcheckdb
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data

    app:
        build: .
        ports:
            - 1337:1337
        command: make run
        depends_on:
            - db
        environment:
            PYTHONUNBUFFERED: 1
            DB_HOST: db
            DB_USER: postgres
            DB_PASSWORD: postgres
            DB_NAME: passcheckdb
        volumes:
            - .:/usr/src/app

volumes:
    pgdata:


